<x-layout.app
  title="FROMS - Stock Movements"
  :assets="[
    'resources/css/Main-styles/main.css',
    'resources/css/Main-styles/sidebar.css',
    'resources/css/Warehouse/stock-movements.css',
    'resources/js/Main-js/sidebar.js'
  ]"
>

  @php
    $movementQuery = \App\Models\Warehouse\StockMovement::query();

    if (request()->filled('search')) {
      $search = trim(request('search'));
      $movementQuery->where(function ($query) use ($search) {
        $query->where('item_name', 'like', "%{$search}%")
          ->orWhere('item_code', 'like', "%{$search}%")
          ->orWhere('reference_no', 'like', "%{$search}%")
          ->orWhere('movement_type', 'like', "%{$search}%")
          ->orWhere('remarks', 'like', "%{$search}%");
      });
    }

    if (request()->filled('type') && request('type') !== 'All Types') {
      $movementQuery->where('movement_type', request('type'));
    }

    if (request('date_filter') === 'Today') {
      $movementQuery->whereDate('created_at', today());
    } elseif (request('date_filter') === 'This Week') {
      $movementQuery->whereBetween('created_at', [now()->startOfWeek(), now()->endOfWeek()]);
    } elseif (request('date_filter') === 'This Month') {
      $movementQuery->whereYear('created_at', now()->year)
        ->whereMonth('created_at', now()->month);
    }

    $stockMovements = $movementQuery->latest()->paginate(20)->withQueryString();
    $totalMovements = \App\Models\Warehouse\StockMovement::count();
    $stockIn = \App\Models\Warehouse\StockMovement::where('movement_type', 'Stock In')->count();
    $stockOut = \App\Models\Warehouse\StockMovement::where('movement_type', 'Stock Out')->count();
    $adjustments = \App\Models\Warehouse\StockMovement::where('movement_type', 'Adjustment')->count();
  @endphp

  <div class="app">
    <x-layout.sidebar
      department="Warehouse"
      subtitle="Warehouse Module"
      icon="fa-warehouse"
      :items="[
        ['label' => 'Dashboard', 'route' => 'warehouse.dashboard', 'icon' => 'fa-table-cells-large'],
        ['label' => 'Inventory', 'route' => 'inventory', 'icon' => 'fa-boxes-stacked'],
        ['label' => 'Part Requests', 'route' => 'part-requests', 'icon' => 'fa-clipboard-list'],
        ['label' => 'Incoming Deliveries', 'route' => 'incoming-deliveries', 'icon' => 'fa-truck-ramp-box'],
        ['label' => 'Stock Movements', 'route' => 'stock-movements', 'icon' => 'fa-right-left'],
      ]"
    />

    <main class="main stock-movement-page">
      <x-layout.topbar
        title="Stock Movements"
        subtitle="Track stock-in, stock-out, and inventory adjustment history"
        notification-count="6"
      />

      <section class="stats-grid stock-movement-stats">
        <x-ui.summary-card label="Total Movements" value="{{ $totalMovements }}" small="Recorded stock transactions" icon="fa-right-left" color="blue" />
        <x-ui.summary-card label="Stock In" value="{{ $stockIn }}" small="Inventory received" icon="fa-arrow-down" color="green" />
        <x-ui.summary-card label="Stock Out" value="{{ $stockOut }}" small="Inventory issued" icon="fa-arrow-up" color="red" />
        <x-ui.summary-card label="Adjustments" value="{{ $adjustments }}" small="Inventory corrections" icon="fa-sliders" color="yellow" />
      </section>

      <section class="table-card stock-movement-card">
        <div class="section-header">
          <div>
            <h2>Stock Movement History</h2>
            <p>Automatic inventory transaction history generated by Warehouse activity.</p>
          </div>
        </div>

        <form action="{{ route('stock-movements') }}" method="GET" class="toolbar stock-movement-toolbar">
          <div class="search-box">
            <i class="fa-solid fa-magnifying-glass"></i>
            <input type="text" name="search" value="{{ request('search') }}" placeholder="Search item, reference no., or movement...">
          </div>

          <div class="filter-group">
            <select name="type" id="movementTypeFilter" onchange="this.form.requestSubmit()">
              @foreach(['All Types', 'Stock In', 'Stock Out', 'Adjustment'] as $type)
                <option value="{{ $type }}" @selected(request('type', 'All Types') === $type)>{{ $type }}</option>
              @endforeach
            </select>
          </div>

          <div class="filter-group">
            <select name="date_filter" id="movementDateFilter" onchange="this.form.requestSubmit()">
              @foreach(['All Dates', 'Today', 'This Week', 'This Month'] as $dateFilter)
                <option value="{{ $dateFilter }}" @selected(request('date_filter', 'All Dates') === $dateFilter)>{{ $dateFilter }}</option>
              @endforeach
            </select>
          </div>
        </form>

        <div class="table-wrap">
          <table class="stock-movement-table">
            <thead>
              <tr>
                <th>Date / Time</th>
                <th>Item / Part</th>
                <th>Reference</th>
                <th>Movement</th>
                <th>Qty</th>
                <th>Previous</th>
                <th>New Stock</th>
                <th>Remarks</th>
              </tr>
            </thead>
            <tbody>
              @forelse($stockMovements as $movement)
                @php
                  $movementClass = match($movement->movement_type) {
                    'Stock In' => 'stock-in',
                    'Stock Out' => 'stock-out',
                    'Adjustment' => 'adjustment',
                    default => 'default',
                  };
                  $movementIcon = match($movement->movement_type) {
                    'Stock In' => 'fa-arrow-down',
                    'Stock Out' => 'fa-arrow-up',
                    'Adjustment' => 'fa-sliders',
                    default => 'fa-right-left',
                  };
                @endphp
                <tr>
                  <td>
                    <div class="movement-date">
                      <span>{{ $movement->created_at->format('M d, Y') }}</span>
                      <small>{{ $movement->created_at->format('h:i A') }}</small>
                    </div>
                  </td>
                  <td>
                    <div class="movement-item">
                      <strong>{{ $movement->item_name }}</strong>
                      @if($movement->item_code)<small>{{ $movement->item_code }}</small>@endif
                    </div>
                  </td>
                  <td>{{ $movement->reference_no ?: '—' }}</td>
                  <td>
                    <span class="movement-badge {{ $movementClass }}">
                      <i class="fa-solid {{ $movementIcon }}"></i>
                      {{ $movement->movement_type }}
                    </span>
                  </td>
                  <td>
                    <strong class="movement-quantity {{ $movementClass }}">
                      {{ $movement->quantity_change > 0 ? '+' : '' }}{{ $movement->quantity_change }}{{ $movement->unit ? ' '.$movement->unit : '' }}
                    </strong>
                  </td>
                  <td>{{ $movement->previous_stock }}</td>
                  <td><strong>{{ $movement->new_stock }}</strong></td>
                  <td class="movement-remarks">{{ $movement->remarks ?: '—' }}</td>
                </tr>
              @empty
                <tr>
                  <td colspan="8" class="empty-stock-movements">
                    <x-ui.empty-state
                      class="stock-movement-empty-state"
                      icon="fa-right-left"
                      title="No stock movements recorded"
                      description="Stock-in, stock-out, and adjustment transactions will appear automatically when inventory changes."
                    />
                  </td>
                </tr>
              @endforelse
            </tbody>
          </table>
        </div>

        <x-ui.table-footer :items="$stockMovements" />
      </section>
    </main>
  </div>
</x-layout.app>
